version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234aaa0987
      MYSQL_DATABASE: userServer
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:alpine
    container_name: redis-store
    restart: always
    ports:
      - "6379:6379"

  grpc:
    build:
      context: .
      dockerfile: ./grpc-manager/Dockerfile
    container_name: grpc-server
    ports:
      - "50051:50051"
    volumes:
      - ./grpc-manager:/app
    depends_on:
      - mysql
      - redis

  app:
    build:
      context: ./ts-express-backend
      dockerfile: Dockerfile
    container_name: express-server
    depends_on:
      - mysql
      - redis
      - grpc
    ports:
      - "3000:3000"
    volumes:
      - ./ts-express-backend:/app
    environment:
      NODE_ENV: development

volumes:
  mysql_data:
