version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234aaa0987
      MYSQL_DATABASE: userServer
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p1234aaa0987"]
      interval: 5s
      retries: 10
    volumes:
      - ./services/database-manager/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  database-manager:
    build:
      context: .
      dockerfile: ./services/database-manager/Dockerfile
    container_name: database-manager
    depends_on:
      mysql:
        condition: service_healthy
    working_dir: /app/services/database-manager
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr=:50052"]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "50052:50052"
    networks:
      - internal
    environment:
      # Optional: make sure these match your .env.docker or are hardcoded here
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: 1234aaa0987
      MYSQL_DATABASE: userServer
      GRPC_PORT: 0.0.0.0:50052



networks:
  internal:
    driver: bridge
