version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234aaa0987
      MYSQL_DATABASE: userServer
    volumes:
      - ./services/database-manager/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - internal

  database-manager:
    build:
      context: .
      dockerfile: ./services/database-manager/Dockerfile
    container_name: database-manager
    depends_on:
      - mysql
    working_dir: /app/services/database-manager
    ports:
      - "50052:50052"
    networks:
      - internal

  redis:
    image: redis:7
    container_name: redis
    networks:
      - internal

  redis-manager:
    build:
      context: .
      dockerfile: ./services/redis-manager/Dockerfile
    container_name: redis-manager
    depends_on:
      - redis
    working_dir: /app/services/redis-manager
    ports:
      - "50053:50053"
    networks:
      - internal

  auth-server:
    build:
      context: .
      dockerfile: ./services/auth-server/Dockerfile
    container_name: auth-server
    depends_on:
      - database-manager
      - redis-manager
    working_dir: /app/services/auth-server
    ports:
    - "50051:50051"
    networks:
      - internal

networks:
  internal:
    driver: bridge
